// Text for the guided tour. Paragraph strings may use **bold** and *italic*.

export const TOUR_TEXT = {
  en: {
    back: 'Exercises',
    tourName: 'How our notes were chosen',
    part: 'Part {n}',
    previous: 'Previous',
    next: 'Next',
    finish: 'Back to the exercises',
    tryIt: 'Try it',
    listen: 'Listen',

    monochord: 'The monochord',
    octaveTarget: 'One octave · C up to the next C',
    spiral: 'The spiral of fifths',
    wholeString: 'the whole string',
    ofString: '{f} of the string',
    pluck: 'Click the string to pluck it',
    octDown: 'Double the length',
    octDownSub: 'an octave lower',
    octUp: 'Halve the length',
    octUpSub: 'an octave higher',
    thirds: 'Divide into thirds',
    thirdsSub: 'keep one third',
    thirdsUsed: 'Already divided — now fold it into the octave',
    tooLow1: 'an octave too low',
    tooLowN: '{n} octaves too low',
    tooHigh1: 'an octave too high',
    tooHighN: '{n} octaves too high',
    nextOctave: 'next C',
    dragHint: 'drag to turn',

    p1Kicker: 'Halves and doubles',
    p1Title: 'The octave',
    p1: [
      'Every note you practise in this app, from C to F♯ to B♭, was chosen for a reason. Over six short pages we will rebuild them from nothing but a single string, following the path that musicians and philosophers took more than two and a half thousand years ago.',
      'Their instrument was the **monochord**: one string stretched over a long wooden box, with a movable bridge underneath. Slide the bridge along and only part of the string is left free to vibrate. The shorter that part, the higher the note.',
      'Something remarkable happens when the bridge sits exactly **half way**. The note is higher, and yet it sounds like the *same note*. Sing the two together with a friend and your voices melt into one. This is the **octave**, and every musical culture we know of hears it this way. The Greeks called it *diapasōn*, “through all the strings”.',
      'In numbers: halving the length **doubles** the frequency, the number of times the string vibrates each second. Doubling the length halves it. Every octave is a ratio of 2 : 1.',
    ],
    p1Try: 'Halve and double the string with the buttons below it. Watch the frequency, and listen to how every C sounds like the same note.',

    p2Kicker: 'Keeping notes in range',
    p2Title: 'Folding into one octave',
    p2: [
      'Because octaves sound alike, a C is a C whether it rumbles at the bottom of a piano or rings at the top. Musicians call this **octave equivalence**, and it is about to become our most useful tool.',
      'Soon we will make *new* notes by dividing the string in other ways. Each new division gives a higher note than the one before, so if we just kept going, our notes would climb forever: past the top of the piano, past the top of human hearing. Notes that far apart are impossible to compare.',
      'The fix is simple. Whenever a note wanders out of range, we move it by whole octaves, halving or doubling the string, until it sits inside **one chosen octave**. Its name doesn’t change, only how high it is. Then all our notes can live side by side, where we can see and hear how they relate.',
    ],
    p2Try: 'Each round gives you a string of a random length. Halve or double it until its note settles inside the octave. Notes that don’t fit will bounce off.',
    p2Round: 'String {n} of {total}',
    p2Done: 'Every string folded into place. That is all the preparation we need.',

    p3Kicker: 'Pythagoras',
    p3Title: 'Dividing by three',
    p3: [
      'Around 530 BC the Greek philosopher **Pythagoras** founded a school in Croton, in southern Italy. His followers believed the whole universe was built from whole numbers, and music was their best evidence.',
      'A later legend tells of Pythagoras walking past a blacksmith’s forge and noticing that some hammers rang sweetly together while others clashed. The story doesn’t work with real hammers, but it works perfectly on a string, and the monochord is where the Pythagoreans made their discovery: the sweetest combinations of notes come from the simplest ratios.',
      'After the octave (2 : 1), the next simplest division is into **three** equal parts. Let one third of the string vibrate and you hear a note an octave *and a fifth* higher: from C, a high G. Double that length to drop it an octave, so two thirds of the string vibrate, and you land on the G just a **perfect fifth** above C. That is the ratio 3 : 2, the most stable-sounding interval after the octave itself.',
    ],
    p3Listen: ['The whole string · C', 'One third · G, an octave and a fifth up', 'Two thirds · G, a fifth up', 'C and G together'],
    p3After: 'Every note has a fifth of its own, and dividing its string into thirds will always find it, an octave too high.',
    p3Try: 'Divide the string into thirds once, then fold the new note back into the octave. Five notes to find.',
    p3Start: 'Start from {note}',
    p3Found: '{a} → {b}: a perfect fifth higher',
    p3Next: 'Next note',
    p3Done: 'Five fifths found. Now let’s see what happens when we keep going.',

    p4Kicker: 'Chains of fifths',
    p4Title: 'The spiral of fifths',
    p4: [
      'If dividing by three gives a new note, we can do it again, starting from the note we just found. C gives G, G gives D, D gives A… each new note a perfect fifth above the last, folded back into our octave.',
      'This chain of fifths is **Pythagorean tuning**, the system medieval Europe sang and played in. Chinese texts from more than two thousand years ago describe almost the same recipe, *sānfēn sǔnyì*, “take away a third, add a third”, for cutting sets of bamboo pitch pipes.',
      'Since every note is folded into the same octave, you might expect the chain to go round in a circle and come back to C. We have drawn it as a spiral, rising as it turns, so that no note can hide another. Fill it in and see where it leads.',
    ],
    p4Try: 'Starting from C, divide into thirds and fold into the octave to fill each empty slot of the spiral.',
    p4Progress: '{n} of 12 fifths',
    p4Skip: 'Fill in the rest for me',
    p4Done: 'Twelve fifths, all the way round. But look at the top of the spiral: the thirteenth note isn’t C. It’s **B♯**, and it doesn’t sit on C at all.',

    p5Kicker: 'A tiny gap',
    p5Title: 'The Pythagorean comma',
    p5: [
      'Twelve fifths take us through every letter name and every sharp, and should bring us home to C. Instead they land on **B♯**, a note slightly *higher* than C.',
      'The arithmetic shows why. Twelve pure fifths multiply the frequency by (3/2)¹² ≈ **129.75**. Seven octaves multiply it by 2⁷ = **128**. Close, but not equal. The difference, a ratio of 531441 : 524288, is about a quarter of a semitone, and it is called the **Pythagorean comma**.',
      'No number of fifths will ever close the gap. Powers of 3 are always odd and powers of 2 are always even, so they can never meet. The spiral carries on forever: after B♯ come F𝄪, C𝄪, G𝄪…',
      'For centuries musicians dealt with this by stopping after eleven fifths and squeezing the last one to fit. That squashed fifth sounded so sour it was nicknamed the **wolf**, because it howled.',
    ],
    p5Listen: 'One after the other, C and B♯ sound almost the same. Played together they fight: listen for a slow “wah-wah-wah” about three and a half times a second. That wobble is the comma.',
    p5Buttons: ['C', 'B♯', 'C and B♯ together', 'Climb the twelve fifths'],
    semitone: 'one semitone',
    comma: 'the comma · 23.5 cents',

    p6Kicker: 'Twelve equal steps',
    p6Title: 'Equal temperament',
    p6: [
      'The solution that finally won was to share the comma out between all twelve fifths. Each fifth is made narrower by about **2 cents**, a cent being a hundredth of a semitone. That is almost too little to hear, and it is exactly enough to close the circle.',
      'Closing the circle means splitting the octave into twelve **equal** steps. Each step up multiplies the frequency by the same number, and twelve steps must double it, so every step is the twelfth root of two:',
    ],
    p6FormulaNote: 'Here *n* is the number of semitones above the starting note f₀. A perfect fifth is seven semitones: 2^(7/12) ≈ 1.4983, a whisker narrower than the pure 1.5.',
    p6History: 'The idea was worked out at almost the same moment on opposite sides of the world: by the Chinese prince **Zhu Zaiyu** in 1584, and by the Flemish mathematician **Simon Stevin** around 1585. Instrument makers adopted it gradually, and by the late 1800s it was the standard tuning for the piano. Nearly every note you hear today is tuned this way, including every note in this app.',
    p6Try: 'Drag the slider from Pythagorean tuning to equal temperament and watch the spiral from above. Turn on the drone to hear C and B♯ together as you slide.',
    pythagorean: 'Pythagorean',
    equal: 'Equal temperament',
    fifthSize: 'Each fifth',
    gapSize: 'From C to B♯',
    cents: '{c} cents',
    droneOn: 'Hear C and B♯ together',
    droneOff: 'Stop the drone',
    playCircle: 'Play the twelve fifths',
    p6Done: 'B♯ and C are now the very same note, and the spiral has closed into the **circle of fifths**: the circle you practise with in Block 3.',
  },

  es: {
    back: 'Ejercicios',
    tourName: 'Cómo se eligieron nuestras notas',
    part: 'Parte {n}',
    previous: 'Anterior',
    next: 'Siguiente',
    finish: 'Volver a los ejercicios',
    tryIt: 'Pruébalo',
    listen: 'Escucha',

    monochord: 'El monocordio',
    octaveTarget: 'Una octava · de Do al siguiente Do',
    spiral: 'La espiral de quintas',
    wholeString: 'la cuerda entera',
    ofString: '{f} de la cuerda',
    pluck: 'Haz clic en la cuerda para pulsarla',
    octDown: 'Duplicar la longitud',
    octDownSub: 'una octava más grave',
    octUp: 'Reducir a la mitad',
    octUpSub: 'una octava más aguda',
    thirds: 'Dividir en tercios',
    thirdsSub: 'quedarse con un tercio',
    thirdsUsed: 'Ya dividida: ahora llévala a la octava',
    tooLow1: 'una octava demasiado grave',
    tooLowN: '{n} octavas demasiado grave',
    tooHigh1: 'una octava demasiado aguda',
    tooHighN: '{n} octavas demasiado aguda',
    nextOctave: 'siguiente Do',
    dragHint: 'arrastra para girar',

    p1Kicker: 'Mitades y dobles',
    p1Title: 'La octava',
    p1: [
      'Todas las notas que practicas en esta aplicación, de Do a Fa♯ o Si♭, se eligieron por una razón. En seis páginas breves vamos a reconstruirlas a partir de una sola cuerda, siguiendo el camino que recorrieron músicos y filósofos hace más de dos mil quinientos años.',
      'Su instrumento era el **monocordio**: una cuerda tensada sobre una caja de madera alargada, con un puente móvil debajo. Al deslizar el puente, solo una parte de la cuerda queda libre para vibrar. Cuanto más corta es esa parte, más aguda es la nota.',
      'Cuando el puente queda justo **en la mitad** ocurre algo notable. La nota es más aguda y, sin embargo, suena como *la misma nota*. Cántalas a la vez con alguien y las dos voces se funden en una. Es la **octava**, y todas las culturas musicales que conocemos la oyen así. Los griegos la llamaban *diapasōn*, «a través de todas las cuerdas».',
      'En números: reducir la longitud a la mitad **duplica** la frecuencia, es decir, las veces que la cuerda vibra cada segundo. Duplicar la longitud la reduce a la mitad. Toda octava es una razón de 2 : 1.',
    ],
    p1Try: 'Reduce a la mitad y duplica la cuerda con los botones de debajo. Fíjate en la frecuencia y escucha cómo cada Do suena como la misma nota.',

    p2Kicker: 'Mantener las notas a raya',
    p2Title: 'Plegar en una sola octava',
    p2: [
      'Como las octavas suenan parecidas, un Do es un Do tanto si retumba en lo más grave del piano como si suena en lo más agudo. Los músicos lo llaman **equivalencia de octava**, y va a ser nuestra herramienta más útil.',
      'Pronto crearemos notas *nuevas* dividiendo la cuerda de otras maneras. Cada nueva división da una nota más aguda que la anterior, así que si siguiéramos sin más, las notas subirían sin fin: más allá del piano, más allá de lo que el oído humano puede captar. Notas tan alejadas son imposibles de comparar.',
      'La solución es sencilla. Cuando una nota se sale de rango, la movemos por octavas enteras, reduciendo a la mitad o duplicando la cuerda, hasta que quede dentro de **una octava elegida**. Su nombre no cambia, solo su altura. Así todas nuestras notas pueden convivir una junto a otra, donde podemos ver y oír cómo se relacionan.',
    ],
    p2Try: 'En cada ronda recibes una cuerda de longitud aleatoria. Redúcela a la mitad o duplícala hasta que su nota se asiente dentro de la octava. Las notas que no caben rebotan.',
    p2Round: 'Cuerda {n} de {total}',
    p2Done: 'Todas las cuerdas plegadas en su sitio. Es toda la preparación que necesitamos.',

    p3Kicker: 'Pitágoras',
    p3Title: 'Dividir entre tres',
    p3: [
      'Hacia el año 530 a. C., el filósofo griego **Pitágoras** fundó una escuela en Crotona, en el sur de Italia. Sus seguidores creían que todo el universo estaba hecho de números enteros, y la música era su mejor prueba.',
      'Una leyenda posterior cuenta que Pitágoras pasó junto a una herrería y notó que algunos martillos sonaban bien juntos y otros chocaban. Con martillos de verdad la historia no funciona, pero con una cuerda funciona a la perfección, y fue en el monocordio donde los pitagóricos hicieron su descubrimiento: las combinaciones más dulces nacen de las razones más sencillas.',
      'Después de la octava (2 : 1), la división más sencilla es en **tres** partes iguales. Si vibra un tercio de la cuerda, oyes una nota una octava *y una quinta* más aguda: desde Do, un Sol agudo. Duplica esa longitud para bajarla una octava, de modo que vibren dos tercios de la cuerda, y llegas al Sol que está justo una **quinta justa** por encima de Do. Es la razón 3 : 2, el intervalo más estable después de la propia octava.',
    ],
    p3Listen: ['La cuerda entera · Do', 'Un tercio · Sol, una octava y una quinta más aguda', 'Dos tercios · Sol, una quinta más aguda', 'Do y Sol juntos'],
    p3After: 'Cada nota tiene su propia quinta, y dividir su cuerda en tercios siempre la encuentra, una octava demasiado aguda.',
    p3Try: 'Divide la cuerda en tercios una vez y luego lleva la nueva nota de vuelta a la octava. Hay cinco notas que encontrar.',
    p3Start: 'Empieza desde {note}',
    p3Found: '{a} → {b}: una quinta justa más aguda',
    p3Next: 'Siguiente nota',
    p3Done: 'Cinco quintas encontradas. Veamos qué pasa si seguimos.',

    p4Kicker: 'Cadenas de quintas',
    p4Title: 'La espiral de quintas',
    p4: [
      'Si dividir entre tres da una nota nueva, podemos repetirlo empezando por la nota que acabamos de encontrar. Do da Sol, Sol da Re, Re da La… cada nota nueva una quinta justa por encima de la anterior, plegada de vuelta a nuestra octava.',
      'Esta cadena de quintas es la **afinación pitagórica**, el sistema con el que cantó y tocó la Europa medieval. Textos chinos de hace más de dos mil años describen casi la misma receta, *sānfēn sǔnyì*, «quitar un tercio, añadir un tercio», para cortar juegos de flautas de bambú.',
      'Como cada nota se pliega en la misma octava, cabría esperar que la cadena diera la vuelta en un círculo y volviera a Do. La hemos dibujado como una espiral que sube a medida que gira, para que ninguna nota tape a otra. Rellénala y mira adónde lleva.',
    ],
    p4Try: 'Empezando por Do, divide en tercios y pliega en la octava para rellenar cada hueco vacío de la espiral.',
    p4Progress: '{n} de 12 quintas',
    p4Skip: 'Rellena el resto por mí',
    p4Done: 'Doce quintas, toda la vuelta. Pero mira arriba de la espiral: la decimotercera nota no es Do. Es **Si♯**, y no cae encima de Do.',

    p5Kicker: 'Un hueco diminuto',
    p5Title: 'La coma pitagórica',
    p5: [
      'Doce quintas recorren todos los nombres de nota y todos los sostenidos, y deberían devolvernos a Do. En cambio llegan a **Si♯**, una nota ligeramente *más aguda* que Do.',
      'La aritmética explica por qué. Doce quintas puras multiplican la frecuencia por (3/2)¹² ≈ **129,75**. Siete octavas la multiplican por 2⁷ = **128**. Cerca, pero no igual. La diferencia, una razón de 531441 : 524288, es más o menos un cuarto de semitono, y se llama **coma pitagórica**.',
      'Ningún número de quintas cerrará nunca el hueco. Las potencias de 3 siempre son impares y las de 2 siempre son pares, así que nunca coinciden. La espiral sigue para siempre: después de Si♯ vienen Fa𝄪, Do𝄪, Sol𝄪…',
      'Durante siglos los músicos lo resolvieron parando tras once quintas y apretando la última para que encajara. Esa quinta aplastada sonaba tan agria que la apodaron el **lobo**, porque aullaba.',
    ],
    p5Listen: 'Una detrás de otra, Do y Si♯ suenan casi iguales. Juntas se pelean: escucha un «uá-uá-uá» lento, unas tres veces y media por segundo. Ese vaivén es la coma.',
    p5Buttons: ['Do', 'Si♯', 'Do y Si♯ juntos', 'Sube las doce quintas'],
    semitone: 'un semitono',
    comma: 'la coma · 23,5 cents',

    p6Kicker: 'Doce pasos iguales',
    p6Title: 'El temperamento igual',
    p6: [
      'La solución que acabó imponiéndose fue repartir la coma entre las doce quintas. Cada quinta se estrecha unos **2 cents**, siendo un cent la centésima parte de un semitono. Es casi imposible de oír, y es exactamente lo que hace falta para cerrar el círculo.',
      'Cerrar el círculo significa dividir la octava en doce pasos **iguales**. Cada paso multiplica la frecuencia por el mismo número, y doce pasos deben duplicarla, así que cada paso es la raíz duodécima de dos:',
    ],
    p6FormulaNote: 'Aquí *n* es el número de semitonos por encima de la nota inicial f₀. Una quinta justa son siete semitonos: 2^(7/12) ≈ 1,4983, un pelo más estrecha que la pura, 1,5.',
    p6History: 'La idea se desarrolló casi a la vez en extremos opuestos del mundo: el príncipe chino **Zhu Zaiyu** en 1584 y el matemático flamenco **Simon Stevin** hacia 1585. Los constructores de instrumentos la adoptaron poco a poco, y a finales del siglo XIX ya era la afinación estándar del piano. Casi todas las notas que oyes hoy están afinadas así, incluidas todas las de esta aplicación.',
    p6Try: 'Arrastra el control desde la afinación pitagórica hasta el temperamento igual y mira la espiral desde arriba. Activa el bordón para oír Do y Si♯ juntos mientras lo deslizas.',
    pythagorean: 'Pitagórica',
    equal: 'Temperamento igual',
    fifthSize: 'Cada quinta',
    gapSize: 'De Do a Si♯',
    cents: '{c} cents',
    droneOn: 'Oír Do y Si♯ juntos',
    droneOff: 'Parar el bordón',
    playCircle: 'Tocar las doce quintas',
    p6Done: 'Si♯ y Do son ahora exactamente la misma nota, y la espiral se ha cerrado en el **círculo de quintas**: el círculo con el que practicas en el Bloque 3.',
  },
}
